# Generated by Django 3.2.16 on 2022-11-28 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('post', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorpost', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('estreno', models.DateTimeField()),
                ('duracion', models.IntegerField()),
                ('sinopsis', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenesposts')),
                ('genero', models.ManyToManyField(blank=True, null=True, to='AppBlog.Genero')),
                ('usuariopost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
