# Generated by Django 3.2.16 on 2022-11-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_remove_peliculas_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
