# Generated by Django 3.2.16 on 2022-11-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_peliculas_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='sinopsis',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='cuerpo1',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='cuerpo2',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
