# Generated by Django 3.2.16 on 2022-11-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_auto_20221129_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=''),
        ),
    ]
