# Generated by Django 3.2.16 on 2022-11-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_peliculas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='Media/posts'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='Media/posts'),
        ),
    ]
