# Generated by Django 3.2.16 on 2022-11-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_auto_20221129_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='cuerpo1',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='cuerpo2',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
