# Generated by Django 3.2.16 on 2022-11-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0008_auto_20221129_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='cuerpo1',
            field=models.TextField(blank=True, max_length=10000000000, null=True),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='cuerpo2',
            field=models.TextField(blank=True, max_length=10000000000, null=True),
        ),
    ]
