# Generated by Django 3.2.16 on 2022-11-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_auto_20221129_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='autorpost',
            new_name='autor_post',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='duracion',
            new_name='duracion_en_min',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='usuariopost',
            new_name='usuario_post',
        ),
    ]
