# Generated by Django 3.2.16 on 2022-11-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_auto_20221129_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='cuerpo1',
            new_name='Primer_cuerpo',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='imagen1',
            new_name='Primer_imagen',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='imagen2',
            new_name='Segunda_imagen',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='cuerpo2',
            new_name='Segundo_cuerpo',
        ),
    ]
