# Generated by Django 4.1.3 on 2022-12-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0012_auto_20221129_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='Primer_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='Segunda_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
