# Generated by Django 3.2.16 on 2022-12-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0013_alter_peliculas_primer_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='Primer_imagen',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
