# Generated by Django 3.2.16 on 2022-12-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0016_auto_20221210_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='autor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
