# Generated by Django 3.2.16 on 2022-12-10 21:38

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0017_alter_peliculas_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='autor',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
