# Generated by Django 3.2.16 on 2022-12-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0023_auto_20221211_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
