# Generated by Django 3.2.16 on 2022-12-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0026_rename_body_comment_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generos',
        ),
    ]
