# Generated by Django 3.2.16 on 2022-12-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0027_delete_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='genero',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
